apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devices-ingress
spec:
  rules:
    - host: devices.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devices-service
                port:
                  number: 80